# Generated by Django 4.0.4 on 2022-05-18 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='parent',
        ),
    ]
