# Generated by Django 4.0.4 on 2022-05-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_rename_score_rating_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='parent',
            new_name='profile',
        ),
    ]
