# Generated by Django 4.0.4 on 2022-05-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0004_rename_parent_rating_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Entry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
