# Generated by Django 4.0.4 on 2022-05-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0007_alter_entry_profile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='off_online',
            field=models.CharField(choices=[('0', 'Online'), ('1', 'In Person')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
